baseURL = 'https://blog.quintschaf.com/'
languageCode = 'en-us'
title = 'Quintschaf Blog'
theme = 'hugo-theme-monochrome'
disqusShortname = 'quintschaf-blog'

[outputs]
home = ["HTML", "RSS", "JSON"]

[build]
writeStats = true

[params]
# SEO
author = 'Quintschaf'
enableOpenGraph = true
enableTwitterCards = true
# Features
enableSiteSearch = true
# Footer
footer = 'Copyright © 2022 Quintschaf GbR'