baseURL = 'https://blog.fivesheep.co/'
languageCode = 'en-us'
title = 'FiveSheep Blog'
theme = 'hugo-theme-monochrome'
# disqusShortname = 'fivesheep-blog'

[outputs]
home = ["HTML", "RSS", "JSON"]

[build]
writeStats = true

[params]
# SEO
author = 'FiveSheep'
enableOpenGraph = true
enableTwitterCards = true
# Features
enableSiteSearch = true
# Footer
footer = 'Copyright © 2024 FiveSheep OÜ, 2022 Quintschaf GbR'

[markup.goldmark.renderer]
unsafe = true
